### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by sertel** [mit-plv/koika#21]
Dear @cpitclaudel ,

We are trying out Koika to run part of an operating system on an FPGA.
In a test case (a.k.a. `Example`) we are using `tc_compute` and `interpret_action` to evaluate an action.
When we do so, we enter an infinite loop.

So far I could only identify two source where this can happen:

1. In type class resolution (https://issuehint.com/issue/coq/coq/16216)
2. In tactics such as `repeat` (https://stackoverflow.com/questions/53750792/can-composing-try-and-repeat-lead-to-an-infinite-loop-in-coq)

I tried to get some debug output on following the instructions shared in the link above but to no avail.
There is quite some code in Koika that uses `repeat` but I was not sure how to debug this properly.  

It is hard to boil this down to a small example that would fit in a bug post.
But if you could possibly find the time, I could share the according repository with you.

Any help would be very much appreciated.

**Comment by cpitclaudel** [comment]
Hi @sertel,

Thanks for trying out Koika!
I suspect that the problem is slow computation rather than an infinite loop, unfortunately.  The `tc_compute` tactic is really just a fancy wrapper around Coq's computation tactics, and they can blow up badly if computation gets blocked on something irreducible.

You mention a test case (an `Example`).  Would it be feasible for that case to use extraction, instead of tc_compute?

**Comment by sertel** [comment]
Hi @cpitclaudel,

thanks for your response.
The problem really does not seem to be slowness. I managed to boil this down to a very small self-contained "test case".
Here is my configuration for the register:

```coq
Require Import Koika.Frontend.

Inductive reg_t :=
| r1
.

Definition R (reg: reg_t) : type :=
  match reg with
  | r1 => bits_t 1
  end.

Definition r (reg: reg_t) : R reg :=
  match reg with
  | r1 => Bits.zero
  end.
```

Then I have the following 3 functions defined:
```coq
Definition f1: UInternalFunction reg_t empty_ext_fn_t :=
  {{ fun f1 (i1: bits_t 1) (i2: bits_t 4) : unit_t =>
       let i11 := i1 in
       let i21 := i2 in
       write1(r1, i11)
  }}.

Definition f2: UInternalFunction reg_t empty_ext_fn_t :=
  {{ fun f2 (i1: bits_t 1) (i2: bits_t 4) (i3 : bits_t 3) : unit_t =>
       let i11 := i1 in
       let i21 := i2 in
       let i31 := i3 in
       write1(r1, i11)
  }}.

Definition f3: UInternalFunction reg_t empty_ext_fn_t :=
  {{ fun f3 (i1: bits_t 1) (i2: bits_t 4) (i3 : bits_t 3) : unit_t =>
       let i11 := i1 in
       let i31 := i3 in
       write1(r1, i11)
  }}.
```
Then I type-check them and turn them into actions:
```coq
Definition tc_f1 :=  tc_function R empty_Sigma f1.
Definition tc_f2 :=  tc_function R empty_Sigma f2.
Definition tc_f3 :=  tc_function R empty_Sigma f3.
```
Then I have some testing utility defined:
```coq
Definition reg_type (idx:reg_t) := R idx.
Definition Env := env_t ContextEnv reg_type.

Definition tc_and_run_action_on_inputs {sig: tsig var_t} {tau} (e:Env) (a:action R empty_Sigma sig tau) (inputs: context _ _) :=
  tc_compute
    (interp_action e empty_sigma inputs log_empty log_empty a).

Definition run {sig: tsig var_t} {tau} (a:action R empty_Sigma sig tau) inputs reg_vals :=
  let e := ContextEnv.(create) reg_vals in
  let c := tc_and_run_action_on_inputs e a inputs in
  let r := match c with
           | Some (l,o,_) => Some (commit_update e l, o)
           | None => None
           end in
  must r.
```
And now I'm ready to give you the examples that I run.
Example 1 runs `f1` without any problems:
```coq
Example test1:
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2" , bits_t _) => Bits.of_nat _ 3
                 }# in

  let (ctxt,_) := run tc_f1 input r in

  let o := Bits.to_nat ctxt.[InfiniteLoop.r1] in

  o = 1.
 reflexivity.
Defined.
```
The infinite loop occurs when running `f2`:
```coq
Example test2:
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2" , bits_t _) => Bits.of_nat _ 3;
   ("i3" , bits_t _) => Bits.of_nat _ 4
                 }# in

  let (ctxt,_) := run tc_f2 input r in

  let o := Bits.to_nat ctxt.[InfiniteLoop.r1] in

  o = 1.
reflexivity.
Defined.
```
I tried a little bit more and interestingly `f3` works again:
```coq
Example test3:
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2" , bits_t _) => Bits.of_nat _ 3;
   ("i3" , bits_t _) => Bits.of_nat _ 4
                 }# in

  let (ctxt,_) := run tc_f3 input r in

  let o := Bits.to_nat ctxt.[InfiniteLoop.r1] in

  o = 1.
reflexivity.
Defined.
```
So the problem seems to surface when I bind all 3 inputs directly to local variables. It seems like the problem occurs only when there are more than 2 inputs to a function because otherwise `f1` and `test1` would also loop infinitely.
Do you have any idea on what may cause this problem?

I have the exact same code from the listings in my file (`InfiniteLoop.v`) with the only difference that `test3` comes before `test2` so I can see `test3` pass.

**Comment by sertel** [comment]
I did some debugging and here is what I found.

When evaluating the functions individually then `vm_compute` is successful while `cbn` enters the infinite loop:
```
Eval vm_compute in tc_f2.
Eval cbn in tc_f2. (* infinite loop *)
```
When evaluating a function that does not deadlock then `vm_compute` is quite fast and `cbn` rather slow:
```
Eval vm_compute in tc_f1. (* fast *)
Eval cbn in tc_f1. (* slow *)
```
This behavior is in line with this [article](http://gallium.inria.fr/blog/coq-eval/) and important for the later analysis.

Again, the test that I was trying to run was this:
```
Example test2:
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2" , bits_t _) => Bits.of_nat _ 3;
   ("i3" , bits_t _) => Bits.of_nat _ 4
                 }# in

  let (ctxt,_) := run tc_f2 input r in

  let o := Bits.to_nat ctxt.[InfiniteLoop.r1] in

  o = 1.
reflexivity.
Defined.
```
Notice the `run` line. It does a destructuring of the result *and* the definition of `run` uses `must` to strip off the `option`.
I defined `run'` which does not use `must` but just returns the `option`.

Then the following does *not* enter the infinite loop:
```
Eval vm_compute in (
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2"   , bits_t _) => Bits.of_nat _ 3;
   ("i3"   , bits_t _) => Bits.of_nat _ 4
                 }# in
  let c := run' tc_f2 input r in
  match c with
    | Some (ctxt, _) => let o := Bits.to_nat ctxt.[r1] in o = 1
    | None => False
  end
).
```
But as soon as I use `must` it does:
```
Eval vm_compute in (
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2"   , bits_t _) => Bits.of_nat _ 3;
   ("i3"   , bits_t _) => Bits.of_nat _ 4
                 }# in
  let c := run' tc_f2 input r in
  match (must c) with
    | (ctxt, _) => let o := Bits.to_nat ctxt.[r1] in o = 1
  end
).
```
Your [article](https://plv.csail.mit.edu/blog/unwrapping-options.html#unwrapping-options), @cpitclaudel, gave me some insights. Thanks for that!

Coq seems to evaluate the term but not the return type of `must`. But as soon as the return type of `must` is destructured, it needs to compute this type. And whenever that happens, it seems to use (a version similar to) `cbn` or `simpl`.

My fix is to use your definition of `unwrap_dec'` instead of `must`. For some reason, that I do not yet understand this seems to resort to `vm_compute` (-like evaluation). I could see this on the behavior, i.e., the time it took to compute this type.

Hence, my final test scheme just uses `unwrap_dec'` and reduces with `vm_compute` explicitly before calling `reflexivity`: (Probably `reflexivity` also calls something like `cbn` or `simpl` internally.)
```
Example test2:
  let input := #{
   ("i1"   , bits_t _) => Bits.of_nat _ 1;
   ("i2"   , bits_t _) => Bits.of_nat _ 3;
   ("i3"   , bits_t _) => Bits.of_nat _ 4
                 }# in

  let (ctxt,_) := unwrap_dec' (run' tc_f2 input r) in

  let o := Bits.to_nat ctxt.[r1] in

  o = 1.
  (* reflexivity. <- infinite loop *)
  (* cbn.          <- infinite loop *)
  (* simpl.       <- infinite loop *)
  vm_compute.
  reflexivity.
Defined.
```

For now, I'm good but it would be great if you could comment on my analysis above to fill the missing gaps.
Also, it might make sense to put the `unwrap_dec'` from the article into some library and maybe even replace `must` in Koika with `unwrap_dec'`.

**Comment by sertel** [comment]
Let me close this issue.
It ended up being about reduction during unification which can be steered via tactics in terms. So `tc_compute` etc. plus the `vm_compute`-based version of `unwrap` from the [article](https://plv.csail.mit.edu/blog/unwrapping-options.html#unwrapping-options).

My key take-away was: avoid using type holes whenever possible.
