### ISSUE TITLE
Translating Koika's bits_t (Vect) to MIT's bbv

### ISSUE THREAD

**Issue by felipelisboa-ml** [mit-plv/koika#22]
Hi,

Is there a particular reason why Koika bitvector's are designed with the non-inductive type `vect` ? Why not use [MIT's bbv ](https://github.com/mit-plv/bbv)?

Context: the Koika implementations I'm working on have to be proven correct against a spec that works with `bbv`, I've written a few functions to translate types (like the one below) but ideally I'd need to define some sort of rewritable equality, I suppose.

```
Fixpoint bbvword_to_bits_sized {sz} (wd : Word.word sz) : bits sz :=
    match wd with
    | Word.WO => vect_nil
    | @Word.WS hd n tl => if (Bool.eqb hd true)
        then {|vhd := true; vtl := bbvword_to_bits_sized tl|}
        else {|vhd := false; vtl := bbvword_to_bits_sized tl|}
    end.
```

**Comment by cpitclaudel** [comment]
Sorry that i didn't answer this right away.  The answer is pretty simple: I had suffered a lot while using bbv, and this representation (in my experience) almost always worked better.  For arithmetic, the representation used by bedrock2 (a Z with a proof of bounds) works even better (but it's not necessarily better for bitwise operations).
