### ISSUE TITLE
"make verilator-tests" results in a failure (cannot find file containing module: 'ext_host_id')

### ISSUE THREAD

**Issue by mbty** [mit-plv/koika#5]
On the other hand, `make cuttlesim-tests` still works fine.
Looks like `examples/rv/etc/sv/ext_host_id.v` was not pushed.
See https://gist.github.com/mbty/1a764c50afd8b169954612a65add433b for full details.

**Comment by cpitclaudel** [comment]
Ah, snap, sorry

**Comment by cpitclaudel** [comment]
Thanks a lot for the report! :)
